services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - .:/docker-entrypoint-initdb.d
    networks:
      - database
  nestjs:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/src
    env_file:
      - .env
    ports:
      - ${PORT}:4000
    depends_on:
      - postgres
    networks:
      - nestjs

networks:
  nestjs:
    driver: bridge
  database:
    driver: bridge
